site_name: UArizona HPC Documentation

nav:
  - Home: index.md
  - Policies:
    - Acceptable Use: policies/acceptable_use/index.md
    - Acknowledgements: policies/acknowledgements/index.md
    - Buy-in: policies/buy_in/index.md
    - Committees: policies/committees/index.md
    - Loss of University Affiliation: policies/loss_of_university_affiliation/index.md
    - Maintenance: policies/maintenance/index.md
    - Special Projects: policies/special_projects/index.md
  - Registration and Access:
    - Account Creation: registration_and_access/account_creation/index.md
    - Account Deletion: registration_and_access/account_deletion/index.md
    - Group Management: registration_and_access/group_management/index.md
    - System Access: registration_and_access/system_access/index.md
    - VPN : registration_and_access/vpn/index.md
  - Storage and Transfers:
    - Storage:
      - Overview: storage_and_transfers/storage/overview/index.md
      - HPC Storage: storage_and_transfers/storage/hpc_storage/index.md
      - Rental Storage: storage_and_transfers/storage/rental_storage/index.md
      - RDAS Storage: storage_and_transfers/storage/rdas_storage/index.md
      - Tier2 AWS Storage: storage_and_transfers/storage/tier2_storage/index.md

  - Software:
    - Overview: software/overview/index.md
    - Modules: software/modules/index.md
    - User Installation Help: software/user_installations/index.md
    - Common Datasets: software/common_datasets/index.md
    - Python and Anaconda: software/python_and_anaconda/index.md
    - R: software/R/index.md
    - Matlab: software/matlab/index.md
    - Perl: software/perl/index.md
    - VSCode Remote Connection: software/vscode_remote_connection/index.md

  - Running Jobs:
    - Overview: running_jobs/overview/index.md
    - Time Allocations: running_jobs/allocations/index.md
    - Job Limits: running_jobs/job_limits/index.md
    - Compute Resources: running_jobs/compute_resources/index.md
    - Open OnDemand: running_jobs/open_on_demand/index.md
    - Interactive Jobs: running_jobs/interactive_jobs/index.md
    - Batch Jobs:
        - Quick Start: running_jobs/batch_jobs/quick_start/index.md
        - Slurm Documentation: running_jobs/batch_jobs/slurm_documentation/index.md
        - Example Batch Jobs: 
            - General Examples: 
                - Using a Pipefail: running_jobs/batch_jobs/example_batch_jobs/general_examples/pipefail/index.md
                - Job Dependencies: running_jobs/batch_jobs/example_batch_jobs/general_examples/job_dependencies/index.md
            - Array and Parallel Examples: 
                - Basic Array Job: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/basic_array/index.md
                - Array Jobs with Text Filenames: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/array_read_filenames/index.md
                - Array Jobs with Multiple Input Parameters: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/array_read_parameters/index.md
                - Basic GNU Parallel Job: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/basic_gnu_parallel_job/index.md
                - Array Job Using GNU Parallel: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/array_and_gnu_parallel/index.md
    
  - User Support and Training:
    - FAQs: 
        - Account Access: support_and_training/faqs/account_access/index.md 
        - General Computing: support_and_training/faqs/general_computing/index.md 
        - Jobs and Scheduling: support_and_training/faqs/jobs_and_scheduling/index.md 
        - Software and Modules: support_and_training/faqs/software_and_modules/index.md 
        - Storage: support_and_training/faqs/storage/index.md 
        - Open OnDemand Issues: support_and_training/faqs/open_on_demand_issues/index.md 
        - Secure Services: support_and_training/faqs/secure_services/index.md 
    - Consulting Services: support_and_training/consulting_services/index.md
    - Workshops: 
        - Intro to HPC: support_and_training/workshops/intro_to_hpc/index.md
        - Intro to Machine Learning on HPC: support_and_training/workshops/intro_to_machine_learning/index.md
        - Intro to Parallel Computing: support_and_training/workshops/intro_to_parallel_computing/index.md
        - Intro to Containers: support_and_training/workshops/intro_to_containers/index.md
        - Intro to Linux: support_and_training/workshops/intro_to_linux/index.md
        - Intro to Visualization: support_and_training/workshops/intro_to_visualization/index.md
        - Data Management Workshops: support_and_training/workshops/data_management_workshops/index.md
    - Best Practices: support_and_training/best_practices/index.md
    - Glossary: support_and_training/glossary/index.md
    - Grants: support_and_training/grants/index.md
    - Community and External Resources: support_and_training/external_resources/index.md
  - Results: results/index.html

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
 
extra_css:
    - assets/stylesheets/extra.css
 

theme:
  name: material
  logo: assets/images/favicon.ico
  custom_dir: docs/overrides
  favicon: assets/images/favicon.ico
  palette:
    primary: custom
    accent: custom
    #primary: teal 
    #accent: amber

  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    
extra:
  generator: false
  social:
    - icon: material/youtube
      link: https://www.youtube.com/@universityofarizonauitsres7597
    - icon: material/at
      link: mailto:hpc-consult@list.arizona.edu
    - icon: material/ticket
      link: https://uarizona.service-now.com/sp?id=sc_cat_item&sys_id=2983102adbd23c109627d90d689619c6&sysparm_category=84d3d1acdbc8f4109627d90d6896191f
    - icon: material/github
      link: https://github.com/UA-ResearchComputing-HPC/ua-researchcomputing-hpc.github.io

