site_name: UArizona HPC Documentation

nav:
  - Policies:
    - Acceptable Use: policies/acceptable_use/index.md
    - Acknowledgements: policies/acknowledgements/index.md
    - Buy-in: policies/buy_in/index.md
    - Committees: policies/committees/index.md
    - Loss of University Affiliation: policies/loss_of_university_affiliation/index.md
    - Maintenance: policies/maintenance/index.md
    - Special Projects: policies/special_projects/index.md
    
  - Resources:
    - Allocations: resources/allocations/index.md
    - Compute Resources: 
      - Compute Resources: resources/compute_resources/compute_resources/index.md
      - Memory vs. CPU Count: resources/compute_resources/job_memory_and_cpu_count/index.md
      - GPU Nodes: resources/compute_resources/gpu_nodes/index.md
    - Research Data Center: resources/data_center/index.md

  - Access:
    - Account Creation: registration_and_access/account_creation/index.md
    - Account Deletion: registration_and_access/account_deletion/index.md
    - Group Management: 
        - Overview: registration_and_access/group_management/overview/index.md
        - Research Groups: registration_and_access/group_management/research_groups/index.md
        - Class Groups: registration_and_access/group_management/class_groups/index.md
        - Delegating Group Management Rights: registration_and_access/group_management/delegating_group_management_rights/index.md
    - System Access: 
        - Overview: registration_and_access/system_access/overview/index.md
        - Web Access: registration_and_access/system_access/web_access/index.md
        - Command Line Access: registration_and_access/system_access/command_line_access/index.md
        - X11 Forwarding: registration_and_access/system_access/x11_forwarding/index.md
        - SSH Keys: registration_and_access/system_access/ssh_keys/index.md
    - VPN : registration_and_access/vpn/index.md

  - Quick Start: 
    - Overview: quick_start/overview/index.md
    - What is HPC?: quick_start/supercomputing_in_plain_english/index.md
    - Common Misconceptions: quick_start/common_misconceptions/index.md
    - Logging In: quick_start/logging_in/index.md
    - Storage and Transfers: quick_start/storage_and_transfers/index.md
    - Accessing Compute Nodes: quick_start/interactive_jobs/index.md
    - Software: quick_start/software/index.md
    - Batch Jobs: quick_start/batch_jobs/index.md
    
  - Storage and Transfers:
    - Storage:
      - Overview: storage_and_transfers/storage/overview/index.md
      - HPC Storage: 
        - Storage Summary: storage_and_transfers/storage/hpc_storage/storage_summary/index.md
        - Checking Your Usage: storage_and_transfers/storage/hpc_storage/checking_your_usage/index.md
        - xdisk: storage_and_transfers/storage/hpc_storage/xdisk/index.md
      - Rental Storage: storage_and_transfers/storage/rental_storage/index.md
      - RDAS Storage: storage_and_transfers/storage/rdas_storage/index.md
      - Tier2 AWS Storage: storage_and_transfers/storage/tier2_storage/index.md
    - Transfers:
      - Overview: storage_and_transfers/transfers/overview/index.md
      - Globus: storage_and_transfers/transfers/globus/index.md
      - FTP/LFTP/SFTP: storage_and_transfers/transfers/sftp_ftp_lftp/index.md
      - SCP: storage_and_transfers/transfers/scp/index.md
      - rsync: storage_and_transfers/transfers/rsync/index.md
      - rclone: storage_and_transfers/transfers/rclone/index.md
      - Cyberduck: storage_and_transfers/transfers/cyberduck/index.md
      - iRods: storage_and_transfers/transfers/irods/index.md

  - Software:
    - Overview: software/overview/index.md
    - Modules: software/modules/index.md
    - User Installation Help: software/user_installations/index.md
    - Common Datasets: software/common_datasets/index.md
    - Popular Software:
      - Python and Anaconda: 
        - Python: software/popular_software/python_and_anaconda/python/index.md
        - Anaconda: software/popular_software/python_and_anaconda/anaconda/index.md
      - R: software/popular_software/R/index.md
      - Matlab: software/popular_software/matlab/index.md
      - Perl: software/popular_software/perl/index.md
      - VSCode Remote Connection: software/popular_software/vscode_remote_connection/index.md
    - Containers: 
      - What are Containers: software/containers/what_are_containers/index.md
      - Containers on HPC: software/containers/containers_on_hpc/index.md
      - Pulling Containers: software/containers/pulling_containers/index.md
      - Building Containers: software/containers/building_containers/index.md
      - Using Containers: software/containers/using_containers/index.md
      - Containers Tutorials: software/containers/containers_tutorials/index.md

  - Running Jobs:
    - Overview: running_jobs/overview/index.md
    - Best Practices: running_jobs/best_practices/index.md
    - Job Limits: running_jobs/job_limits/index.md
    - Open OnDemand:
      - Overview:  running_jobs/open_on_demand/overview/index.md
      - File Browser: running_jobs/open_on_demand/file_browser/index.md
      - Shell Access: running_jobs/open_on_demand/shell_access/index.md
      - Job Viewer and Composer: running_jobs/open_on_demand/job_viewer_and_composer/index.md
      - Graphical Applications: running_jobs/open_on_demand/graphical_applications/index.md
    - Interactive Jobs: running_jobs/interactive_jobs/index.md
    - Batch Jobs: 
        - Slurm Documentation: running_jobs/batch_jobs/slurm_documentation/index.md
        - Example Batch Jobs: 
            - General Examples: 
                - Using a Pipefail: running_jobs/batch_jobs/example_batch_jobs/general_examples/pipefail/index.md
                - Job Dependencies: running_jobs/batch_jobs/example_batch_jobs/general_examples/job_dependencies/index.md
            - Array and Parallel Examples: 
                - Basic Array Job: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/basic_array/index.md
                - Array Jobs with Text Filenames: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/array_read_filenames/index.md
                - Array Jobs with Multiple Input Parameters: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/array_read_parameters/index.md
                - Basic GNU Parallel Job: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/basic_gnu_parallel_job/index.md
                - Array Job Using GNU Parallel: running_jobs/batch_jobs/example_batch_jobs/array_and_parallel_examples/array_and_gnu_parallel/index.md
    
  - Support:
    - Consulting Services: support_and_training/consulting_services/index.md
    - FAQs: 
        - Account Access: support_and_training/faqs/account_access/index.md 
        - General Computing: support_and_training/faqs/general_computing/index.md 
        - Jobs and Scheduling: support_and_training/faqs/jobs_and_scheduling/index.md 
        - Software and Modules: support_and_training/faqs/software_and_modules/index.md 
        - Storage:
            - HPC Storage: support_and_training/faqs/storage/hpc/index.md
            - Rental Storage: support_and_training/faqs/storage/rental/index.md
            - R-DAS Storage: support_and_training/faqs/storage/rdas/index.md
            - Tier 2 AWS Storage: support_and_training/faqs/storage/aws/index.md
        - Open OnDemand Issues: support_and_training/faqs/open_on_demand_issues/index.md 
        - Secure Services: support_and_training/faqs/secure_services/index.md 
    - Workshops: 
        - Intro to HPC: support_and_training/workshops/intro_to_hpc/index.md
        - Intro to Machine Learning on HPC: 
            - Python: support_and_training/workshops/intro_to_machine_learning/python/index.md
            - R: support_and_training/workshops/intro_to_machine_learning/R/index.md
        - Intro to Parallel Computing: support_and_training/workshops/intro_to_parallel_computing/index.md
        - Intro to Containers: support_and_training/workshops/intro_to_containers/index.md
        - Intro to Linux: support_and_training/workshops/intro_to_linux/index.md
        - Intro to Visualization: support_and_training/workshops/intro_to_visualization/index.md
        - Data Management Workshops: support_and_training/workshops/data_management_workshops/index.md
    - Best Practices: support_and_training/best_practices/index.md
    - Glossary: support_and_training/glossary/index.md
    - Grants: support_and_training/grants/index.md
    - Community and External Resources: support_and_training/external_resources/index.md

  - Secure Services:
    - Overview: secure_hpc/overview/index.md
    - Prerequisites: secure_hpc/prerequisites/index.md
    - Access: secure_hpc/access/index.md
    - Storage and Transfers: secure_hpc/storage_and_transfers/index.md

  - Results: results/index.md
  


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.critic
  
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
 
extra_css:
    - assets/stylesheets/extra.css
 

theme:
  name: material
  logo: assets/images/favicon.ico
  custom_dir: docs/overrides
  favicon: assets/images/favicon.ico
  palette:
    primary: custom
    accent: custom
  icon: 
    annotation: material/star-four-points-circle

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.path
    - toc.integrate
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - navigation.top
    
extra:
  generator: false
  social:
    - icon: material/youtube
      link: https://www.youtube.com/@universityofarizonauitsres7597
      name: Training videos
    - icon: material/at
      link: mailto:hpc-consult@list.arizona.edu
      name: HPC consulting
    - icon: material/help-circle-outline
      link: https://uarizona.service-now.com/sp?id=sc_cat_item&sys_id=2983102adbd23c109627d90d689619c6&sysparm_category=84d3d1acdbc8f4109627d90d6896191f
      name: Submit a help ticket
    - icon: material/web
      link: https://ood.hpc.arizona.edu/pun/sys/dashboard
      name: Open OnDemand
    - icon: material/account
      link: https://portal.hpc.arizona.edu/portal/
      name: User portal

copyright: University of Arizona Research Computing